def get_model_layers(model_name):
    if 'timesformer_attn_s' == model_name:
        output_hook_list = [
            'backbone.transformer_layers.layers.11.attentions.1.proj_drop', 
            'backbone.transformer_layers.layers.10.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.9.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.8.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.7.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.6.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.5.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.4.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.3.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.2.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.1.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.0.attentions.1.proj_drop',
            ]
        output_hook_list.reverse()
    elif 'timesformer_attn_t' == model_name:
        output_hook_list = [
            'backbone.transformer_layers.layers.11.attentions.0.proj_drop', 
            'backbone.transformer_layers.layers.10.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.9.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.8.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.7.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.6.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.5.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.4.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.3.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.2.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.1.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.0.attentions.0.proj_drop',
            ]
        output_hook_list.reverse()
    elif 'timesformer_attn_st' == model_name:
        output_hook_list = [
            'backbone.transformer_layers.layers.11.attentions.0.proj_drop', 
            'backbone.transformer_layers.layers.11.attentions.1.proj_drop', 
            'backbone.transformer_layers.layers.10.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.10.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.9.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.9.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.8.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.8.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.7.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.7.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.6.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.6.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.5.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.5.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.4.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.4.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.3.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.3.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.2.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.2.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.1.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.1.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.0.attentions.0.proj_drop',
            'backbone.transformer_layers.layers.0.attentions.1.proj_drop',
            ]
        output_hook_list.reverse()
    elif 'timesformer_all' == model_name:
        output_hook_list = [
            'backbone.transformer_layers.layers.11.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.11.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.10.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.10.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.9.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.9.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.8.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.8.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.7.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.7.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.6.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.6.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.5.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.5.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.4.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.4.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.3.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.3.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.2.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.2.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.1.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.1.attentions.1.proj_drop',
            'backbone.transformer_layers.layers.0.ffns.0.dropout_layer',
            'backbone.transformer_layers.layers.0.attentions.1.proj_drop',
            ]
        output_hook_list.reverse()
    elif 'timesformer' == model_name:
        output_hook_list = [
            'backbone.transformer_layers.layers.11', 
            'backbone.transformer_layers.layers.10',
            'backbone.transformer_layers.layers.9',
            'backbone.transformer_layers.layers.8',
            'backbone.transformer_layers.layers.7',
            'backbone.transformer_layers.layers.6',
            'backbone.transformer_layers.layers.5',
            'backbone.transformer_layers.layers.4',
            'backbone.transformer_layers.layers.3',
            'backbone.transformer_layers.layers.2',
            'backbone.transformer_layers.layers.1',
            'backbone.transformer_layers.layers.0',
            ]
        output_hook_list.reverse()
    elif 'slowfast_slow' == model_name:
        output_hook_list = [
            'backbone.slow_path.layer1.0',
            'backbone.slow_path.layer1.1',
            'backbone.slow_path.layer1.2',
            'backbone.slow_path.layer2.0',
            'backbone.slow_path.layer2.1',
            'backbone.slow_path.layer2.2',
            'backbone.slow_path.layer2.3',
            'backbone.slow_path.layer3.0',
            'backbone.slow_path.layer3.1',
            'backbone.slow_path.layer3.2',
            'backbone.slow_path.layer3.3',
            'backbone.slow_path.layer3.4',
            'backbone.slow_path.layer3.5',
            'backbone.slow_path.layer4.0',
            'backbone.slow_path.layer4.1',
            'backbone.slow_path.layer4.2',
            ]
    elif 'slowfast' == model_name:
        output_hook_list = [
            'backbone.slow_path.layer1.0',
            'backbone.slow_path.layer1.1',
            'backbone.slow_path.layer1.2',
            'backbone.slow_path.layer2.0',
            'backbone.slow_path.layer2.1',
            'backbone.slow_path.layer2.2',
            'backbone.slow_path.layer2.3',
            'backbone.slow_path.layer3.0',
            'backbone.slow_path.layer3.1',
            'backbone.slow_path.layer3.2',
            'backbone.slow_path.layer3.3',
            'backbone.slow_path.layer3.4',
            'backbone.slow_path.layer3.5',
            'backbone.slow_path.layer4.0',
            'backbone.slow_path.layer4.1',
            'backbone.slow_path.layer4.2',
            'backbone.fast_path.layer1.0',
            'backbone.fast_path.layer1.1',
            'backbone.fast_path.layer1.2',
            'backbone.fast_path.layer2.0',
            'backbone.fast_path.layer2.1',
            'backbone.fast_path.layer2.2',
            'backbone.fast_path.layer2.3',
            'backbone.fast_path.layer3.0',
            'backbone.fast_path.layer3.1',
            'backbone.fast_path.layer3.2',
            'backbone.fast_path.layer3.3',
            'backbone.fast_path.layer3.4',
            'backbone.fast_path.layer3.5',
            'backbone.fast_path.layer4.0',
            'backbone.fast_path.layer4.1',
            'backbone.fast_path.layer4.2',
            ]
    elif 'slowfast_fast' == model_name:
        output_hook_list = [
            'backbone.fast_path.layer1.0',
            'backbone.fast_path.layer1.1',
            'backbone.fast_path.layer1.2',
            'backbone.fast_path.layer2.0',
            'backbone.fast_path.layer2.1',
            'backbone.fast_path.layer2.2',
            'backbone.fast_path.layer2.3',
            'backbone.fast_path.layer3.0',
            'backbone.fast_path.layer3.1',
            'backbone.fast_path.layer3.2',
            'backbone.fast_path.layer3.3',
            'backbone.fast_path.layer3.4',
            'backbone.fast_path.layer3.5',
            'backbone.fast_path.layer4.0',
            'backbone.fast_path.layer4.1',
            'backbone.fast_path.layer4.2',
            ]
    elif 'i3d' == model_name:
        output_hook_list = [
            'backbone.layer1.0',
            'backbone.layer1.1',
            'backbone.layer1.2',
            'backbone.layer2.0',
            'backbone.layer2.1',
            'backbone.layer2.2',
            'backbone.layer2.3',
            'backbone.layer3.0',
            'backbone.layer3.1',
            'backbone.layer3.2',
            'backbone.layer3.3',
            'backbone.layer3.4',
            'backbone.layer3.5',
            'backbone.layer4.0',
            'backbone.layer4.1',
            'backbone.layer4.2',
            ]
    elif 'x3d' == model_name:
        output_hook_list = [
            'backbone.layer1.0',
            'backbone.layer1.1',
            'backbone.layer1.2',
            'backbone.layer2.0',
            'backbone.layer2.1',
            'backbone.layer2.2',
            'backbone.layer2.3',
            'backbone.layer2.4',
            'backbone.layer3.0',
            'backbone.layer3.1',
            'backbone.layer3.2',
            'backbone.layer3.3',
            'backbone.layer3.4',
            'backbone.layer3.5',
            'backbone.layer3.6',
            'backbone.layer3.7',
            'backbone.layer3.8',
            'backbone.layer3.9',
            'backbone.layer3.10',
            'backbone.layer4.0',
            'backbone.layer4.1',
            'backbone.layer4.2',
            'backbone.layer4.3',
            'backbone.layer4.4',
            'backbone.layer4.5',
            'backbone.layer4.6',
        ]
    elif 'x3d_cls' == model_name:
        output_hook_list = [
            'backbone.conv5',
            'cls_head.fc1'
        ]
    elif 'mvit' == model_name:
        output_hook_list = [
            #'backbone.patch_embed',
            'backbone.blocks.0',
            'backbone.blocks.1',
            'backbone.blocks.2',
            'backbone.blocks.3',
            'backbone.blocks.4',
            'backbone.blocks.5',
            'backbone.blocks.6',
            'backbone.blocks.7',
            'backbone.blocks.8',
            'backbone.blocks.9',
            'backbone.blocks.10',
            'backbone.blocks.11',
            'backbone.blocks.12',
            'backbone.blocks.13',
            'backbone.blocks.14',
            'backbone.blocks.15',
            'backbone.blocks.16',
            'backbone.blocks.17',
            'backbone.blocks.18',
            'backbone.blocks.19',
            'backbone.blocks.20',
            'backbone.blocks.21',
            'backbone.blocks.22',
            'backbone.blocks.23',
        ]
    elif 'mvit_all' == model_name:
        output_hook_list = [
            #'backbone.patch_embed',
            'backbone.blocks.0.attn',
            'backbone.blocks.0.mlp',
            'backbone.blocks.1.attn',
            'backbone.blocks.1.mlp',
            'backbone.blocks.2.attn',
            'backbone.blocks.2.mlp',
            'backbone.blocks.3.attn',
            'backbone.blocks.3.mlp',
            'backbone.blocks.4.attn',
            'backbone.blocks.4.mlp',
            'backbone.blocks.5.attn',
            'backbone.blocks.5.mlp',
            'backbone.blocks.6.attn',
            'backbone.blocks.6.mlp',
            'backbone.blocks.7.attn',
            'backbone.blocks.7.mlp',
            'backbone.blocks.8.attn',
            'backbone.blocks.8.mlp',
            'backbone.blocks.9.attn',
            'backbone.blocks.9.mlp',
            'backbone.blocks.10.attn',
            'backbone.blocks.10.mlp',
            'backbone.blocks.11.attn',
            'backbone.blocks.11.mlp',
            'backbone.blocks.12.attn',
            'backbone.blocks.12.mlp',
            'backbone.blocks.13.attn',
            'backbone.blocks.13.mlp',
            'backbone.blocks.14.attn',
            'backbone.blocks.14.mlp',
            'backbone.blocks.15.attn',
            'backbone.blocks.15.mlp',
            'backbone.blocks.16.attn',
            'backbone.blocks.16.mlp',
            'backbone.blocks.17.attn',
            'backbone.blocks.17.mlp',
            'backbone.blocks.18.attn',
            'backbone.blocks.18.mlp',
            'backbone.blocks.19.attn',
            'backbone.blocks.19.mlp',
            'backbone.blocks.20.attn',
            'backbone.blocks.20.mlp',
            'backbone.blocks.21.attn',
            'backbone.blocks.21.mlp',
            'backbone.blocks.22.attn',
            'backbone.blocks.22.mlp',
            'backbone.blocks.23.attn',
            'backbone.blocks.23.mlp',
        ]
    elif 'videomae_s' == model_name:
        output_hook_list = [
            'backbone.blocks.0',
            'backbone.blocks.1',
            'backbone.blocks.2',
            'backbone.blocks.3',
            'backbone.blocks.4',
            'backbone.blocks.5',
            'backbone.blocks.6',
            'backbone.blocks.7',
            'backbone.blocks.8',
            'backbone.blocks.9',
            'backbone.blocks.10',
            'backbone.blocks.11',
        ]
    elif 'videomae_s_attn' == model_name:
        output_hook_list = [
            'backbone.blocks.0.attn.proj_drop',
            'backbone.blocks.1.attn.proj_drop',
            'backbone.blocks.2.attn.proj_drop',
            'backbone.blocks.3.attn.proj_drop',
            'backbone.blocks.4.attn.proj_drop',
            'backbone.blocks.5.attn.proj_drop',
            'backbone.blocks.6.attn.proj_drop',
            'backbone.blocks.7.attn.proj_drop',
            'backbone.blocks.8.attn.proj_drop',
            'backbone.blocks.9.attn.proj_drop',
            'backbone.blocks.10.attn.proj_drop',
            'backbone.blocks.11.attn.proj_drop',
        ]
    elif 'videomae_b' == model_name:
        output_hook_list = [
            'backbone.blocks.0',
            'backbone.blocks.1',
            'backbone.blocks.2',
            'backbone.blocks.3',
            'backbone.blocks.4',
            'backbone.blocks.5',
            'backbone.blocks.6',
            'backbone.blocks.7',
            'backbone.blocks.8',
            'backbone.blocks.9',
            'backbone.blocks.10',
            'backbone.blocks.11',
        ]
    elif 'videomae_b_attn' == model_name:
        output_hook_list = [
            'backbone.blocks.0.attn.proj_drop',
            'backbone.blocks.1.attn.proj_drop',
            'backbone.blocks.2.attn.proj_drop',
            'backbone.blocks.3.attn.proj_drop',
            'backbone.blocks.4.attn.proj_drop',
            'backbone.blocks.5.attn.proj_drop',
            'backbone.blocks.6.attn.proj_drop',
            'backbone.blocks.7.attn.proj_drop',
            'backbone.blocks.8.attn.proj_drop',
            'backbone.blocks.9.attn.proj_drop',
            'backbone.blocks.10.attn.proj_drop',
            'backbone.blocks.11.attn.proj_drop',
        ]
    elif 'videomae_l' == model_name:
        output_hook_list = [
            'backbone.blocks.0',
            'backbone.blocks.1',
            'backbone.blocks.2',
            'backbone.blocks.3',
            'backbone.blocks.4',
            'backbone.blocks.5',
            'backbone.blocks.6',
            'backbone.blocks.7',
            'backbone.blocks.8',
            'backbone.blocks.9',
            'backbone.blocks.10',
            'backbone.blocks.11',
            'backbone.blocks.12',
            'backbone.blocks.13',
            'backbone.blocks.14',
            'backbone.blocks.15',
            'backbone.blocks.16',
            'backbone.blocks.17',
            'backbone.blocks.18',
            'backbone.blocks.19',
            'backbone.blocks.20',
            'backbone.blocks.21',
            'backbone.blocks.22',
            'backbone.blocks.23',
        ]
    elif 'videomae_l_attn' == model_name:
        output_hook_list = [
            'backbone.blocks.0.attn.proj_drop',
            'backbone.blocks.1.attn.proj_drop',
            'backbone.blocks.2.attn.proj_drop',
            'backbone.blocks.3.attn.proj_drop',
            'backbone.blocks.4.attn.proj_drop',
            'backbone.blocks.5.attn.proj_drop',
            'backbone.blocks.6.attn.proj_drop',
            'backbone.blocks.7.attn.proj_drop',
            'backbone.blocks.8.attn.proj_drop',
            'backbone.blocks.9.attn.proj_drop',
            'backbone.blocks.10.attn.proj_drop',
            'backbone.blocks.11.attn.proj_drop',
            'backbone.blocks.12.attn.proj_drop',
            'backbone.blocks.13.attn.proj_drop',
            'backbone.blocks.14.attn.proj_drop',
            'backbone.blocks.15.attn.proj_drop',
            'backbone.blocks.16.attn.proj_drop',
            'backbone.blocks.17.attn.proj_drop',
            'backbone.blocks.18.attn.proj_drop',
            'backbone.blocks.19.attn.proj_drop',
            'backbone.blocks.20.attn.proj_drop',
            'backbone.blocks.21.attn.proj_drop',
            'backbone.blocks.22.attn.proj_drop',
            'backbone.blocks.23.attn.proj_drop',
        ]
    elif 'r2plus1d' == model_name:
        output_hook_list = [
            'backbone.layer1.0',
            'backbone.layer1.1',
            'backbone.layer1.2',
            'backbone.layer2.0',
            'backbone.layer2.1',
            'backbone.layer2.2',
            'backbone.layer2.3',
            'backbone.layer3.0',
            'backbone.layer3.1',
            'backbone.layer3.2',
            'backbone.layer3.3',
            'backbone.layer3.4',
            'backbone.layer3.5',
            'backbone.layer4.0',
            'backbone.layer4.1',
            'backbone.layer4.2',
        ]
    elif 'videoclip' == model_name:
        output_hook_list = [
            'backbone.model.video_encoder.fc',
#            'backbone.model.video_encoder.text_module',
            'backbone.model.model.video_encoder.videomlp',
            'backbone.model.model.video_encoder.bert.encoder.layer.1',
            'backbone.model.model.video_encoder.bert.encoder.layer.2',
            'backbone.model.model.video_encoder.bert.encoder.layer.3',
            'backbone.model.model.video_encoder.bert.encoder.layer.4',
            'backbone.model.model.video_encoder.bert.encoder.layer.5',
            'backbone.model.model.video_encoder.bert.pooler'

        ]
    else:
        print('not defined model {}'.format(model_name))
    return output_hook_list